version: '3'
services:
  angular-app:
    build: .
    ports:
      - "80:80"
#    volumes:
#      - ./dist/pruebas_angular/browser:/usr/share/nginx/html
#    container_name: angular-nginx
    restart: always
